### ISSUE TITLE
`inochi2d.core.nodes.tmp` package missing

### ISSUE THREAD

**Issue by 20kdc** [Inochi2D/inochi2d#20]
During an `inochi-session` compile with the latest local repository of whatever I found needed replacing, on dub `DUB version 1.29.1, built on Jul 12 2022`, DMD `DMD64 D Compiler v2.100.1`, the following error occurred.
```
../inochi2d/source/inochi2d/core/nodes/package.d(22,15): Error: unable to read module `tmp`
../inochi2d/source/inochi2d/core/nodes/package.d(22,15):        Expected 'inochi2d/core/nodes/tmp.d' or 'inochi2d/core/nodes/tmp/package.d' in one of the following import paths:
```
I'm not sure how this occurred, but I have confirmed the package is referred to and doesn't show up.
Sorry for any trouble.

**Comment by LunaTheFoxgirl** [comment]
Pushed a fix, sorry for the inconvenience

**Comment by 20kdc** [comment]
Ah, thank you!
