### ISSUE TITLE
Asdf support will be continued

### ISSUE THREAD

**Issue by 9il** [Inochi2D/inochi2d#21]
Hi folks, we will continue to support both mir-ion and asdf. Asdf is used in production and it will get up-to-date updates with mir-algorithm and new compilers. I wanted to replace it with mir-ion everywhere but finally, I have given up.

**Comment by LunaTheFoxgirl** [comment]
For now we'll be keeping fghj around, but I'm open to pulling in from upstream while keeping our Inochi2D specific patches (which are not really useful outside of Inochi2D)

**Comment by 9il** [comment]
Out of interest, what are these are used for? I wonder if mir-ion already has an alternative for them.

**Comment by LunaTheFoxgirl** [comment]
Mostly just specific patches to account for weird struct layouts in some of the dependencies we use and Inochi2D itself.
Nothing really too useful to other people

**Comment by LunaTheFoxgirl** [comment]
\+ there's some more of those planned, but yeah.

**Comment by LunaTheFoxgirl** [comment]
If I do come up with something I think would be useful upstream I'll see about getting it contributed back upstream when I have the time, though.
