### ISSUE TITLE
Virtual Space does not clear edit window on deletion.

### ISSUE THREAD

**Issue by gatewaytofredom** [Inochi2D/inochi2d#25]
In the attached image you can see an example of the editing window not being cleared after a virtual space was deleted. 

![image](https://user-images.githubusercontent.com/24724006/198816891-39055290-ed44-4e85-a55f-f52c302c4d51.png)

**Comment by LunaTheFoxgirl** [comment]
You've reported this in the wrong repository, could you move it to the inochi-session repo, using our bug report template?

https://github.com/Inochi2D/inochi-session/issues/new?assignees=&labels=bug&template=bug-report.yml&title=%5BBUG%5D
