### ISSUE TITLE
Random characters appended in text boxes.

### ISSUE THREAD

**Issue by gatewaytofredom** [Inochi2D/inochi2d#26]
When creating a virtual space profile 'a??' was appended to the name I typed for the space.
Sometimes it also affects the osf_bind_port entry box. When you click the textbox the appended characters are removed, but may re-appear in subsequent edits.

![image](https://user-images.githubusercontent.com/24724006/198816991-f6855bce-aadd-4cb3-bc13-55ef240e8ed6.png)

**Comment by gatewaytofredom** [comment]
Here's a screenshot of the osf_bind_port being affected. I never entered the question mark into the box.

![image](https://user-images.githubusercontent.com/24724006/198817310-288fb1e5-60ce-46ff-8030-95ff675b0da4.png)

**Comment by LunaTheFoxgirl** [comment]
Fixing this bug properly depends on string_view being merged in imgui. Problem is that strings in DLang are length denoted while imgui currently checks for null terminators.

**Comment by LunaTheFoxgirl** [comment]
Please report this issue in the Inochi Sesion repo
