### ISSUE TITLE
Is the data structure for animations correct?

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi2d#40]
In the current data structure for animations:

- Animations is an object;
- Each animation is a property with the property name same as Animation name.

If we refer to parameters, shouldn't this be:

- Animations is an Array of Object;
- Each object has properties which is timestep, animationWeight, lanes, etc... AND animationName.

This way parameters, animations and bindings from Session will have a somewhat consistent structure.

**Comment by LunaTheFoxgirl** [comment]
Animation being indexed by name is more an optimization thing, but yeah, we should probably chose to write one or the other out to file instead of both...

**Comment by LunaTheFoxgirl** [comment]
After looking through it, the data structure is as intended. The reason being is that Animations use their name as a key, as such the key should be unique. Parameters on the other hand is indexed by their UUID, as such multiple parameters can share a name.
