### ISSUE TITLE
Add Support for More Blending Modes

### ISSUE THREAD

**Issue by helloar14** [Inochi2D/inochi2d#42]
More blending modes will be great, maybe on par with CSS blending modes if possible: https://www.w3schools.com/cssref/pr_mix-blend-mode.php

Note: I feel like this is not a common problem among other users so feel free to discard if not many people think this is important/useful.

**Comment by LunaTheFoxgirl** [comment]
I've managed to add Lighten, Exclusion and Subtract, but that's about all we can add more without extensions that many engines may not support

**Comment by LunaTheFoxgirl** [comment]
Fixed as of https://github.com/Inochi2D/inochi2d/commit/8aa324781b81f60531560ceaf547e4a12f720854
