### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by TwinkyBellCYaGirl2** [Inochi2D/inochi2d#44]
Hello @LunaTheFoxgirl , I love how everything is going with inochi 2D! But there’s a minor issue- the package Idc2 failed to open. Do you know how to fix this?

Kind regards, 

Twinky
![image](https://github.com/Inochi2D/inochi2d/assets/73546755/a59a3fe6-1f3b-4597-b82f-7cd4d53c766c)

**Comment by LunaTheFoxgirl** [comment]
The LDC2 you have on your system is too old to compile Inochi Creator. You'll need to install a newer version of LDC2

**Comment by grillo-delmal** [comment]
Just wanted to add: The project currently provides stable releases for aarch64 through flathub: https://flathub.org/apps/com.inochi2d.inochi-creator

**Comment by TwinkyBellCYaGirl2** [comment]
I got the app from flathub like you said but it keeps closing as soon as I to the command flatpak run com.inochi2d.inochi-creator. Is it because of the old version of LCD2?

**Comment by LunaTheFoxgirl** [comment]
> I got the app from flathub like you said but it keeps closing as soon as I to the command flatpak run com.inochi2d.inochi-creator. Is it because of the old version of LCD2?

Seeing as it's an ARM device you're using (Raspberry Pi?) you may need to force the device to pretend it supports more graphics card features than it actually does. I'm not sure how you do this with flatpak though, some Mesa env vars that need to be set.

**Comment by TwinkyBellCYaGirl2** [comment]
The arm device is debian i think

**Comment by LunaTheFoxgirl** [comment]
> The arm device is debian i think

Wait are you using WSL to run it? Inochi2D will not run under Windows Subsystem for Linux. We don't have arm windows builds at the moment, though.

**Comment by TwinkyBellCYaGirl2** [comment]
No, I have chrome os build for arm linux, im redoing my steps to make sure i didnt type something else.

**Comment by LunaTheFoxgirl** [comment]
Ah, we do not currently support Chrome OS, and I don't think their graphics drivers are made to support Inochi2D either.
This may change in the future, but for now I don't think you'll be able to run it without replacing chrome os with a full linux install with appropriate drivers.
