### ISSUE TITLE
[Feature Request] expressions parameter.

### ISSUE THREAD

**Issue by 00pandora00** [Inochi2D/inochi2d#53]
### Validations

- [X] I have checked for similar feature requests and could not find any.
- [X] I have made sure this is not an already-existing feature.

### Description

expression parameter. 

### Suggested solution

the idea is simple: a type of parameter that when is on (1) show some elements, and when is off(0) hide them.

Note: i think live2d works in a similar way.

### Alternative solution

Note2: i dont know if this characteristics is already in Inochi2d (if that is the case, helppppppp!!! i cant fine tutorials)

**Comment by seagetch** [comment]
You can change opacity value from inspector panel to show/hide elements.

**Comment by 00pandora00** [comment]
> You can change opacity value from inspector panel to show/hide elements.


true. but in principle I can't make animations with that (or at least I don't know how).
  I need to be able to control opasity the same way I control, for example, the eyes.

**Comment by LunaTheFoxgirl** [comment]
Opacity of elements can be adjusted by parameters, as such you can just bind the opacity of elements you want to hide and show to a parameter to do expressions.

**Comment by 00pandora00** [comment]
> Opacity of elements can be adjusted by parameters, as such you can just bind the opacity of elements you want to hide and show to a parameter to do expressions.

how do i bind the opacity to a parameter? (I'm sorry for being so insistent, but I can't find tutorials)

**Comment by LunaTheFoxgirl** [comment]
In Inochi Creator
1. Arm a Parameter
2. Select the node you want to affect the opacity of using the right click menu, or the Nodes list
3. In the inspector, adjust the opacity, the current keypoint of the armed parameter will then have that opacity change bound.

**Comment by 00pandora00** [comment]
> In Inochi Creator
> 
>     1. Arm a Parameter
> 
>     2. Select the node you want to affect the opacity of using the right click menu, or the Nodes list
> 
>     3. In the inspector, adjust the opacity, the current keypoint of the armed parameter will then have that opacity change bound.

thank youuuuu sooooooo muchhhhhh!!!!!!!
