### ISSUE TITLE
Potentially use premultiplied alpha

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Inochi2D/inochi2d#6]
Consideration is needed whether Inochi2D should use premultiplied alpha when rendering or whether it should use straight alpha.

**Comment by ItsRogueRen** [comment]
I'm all for whichever is more efficient and a lighter load on your PC.

**Comment by LunaTheFoxgirl** [comment]
There should be no performance impact by using premultiplied alpha, I just need to wrap my head around getting it working properly

**Comment by LunaTheFoxgirl** [comment]
We're switched over to premultipled alpha now
